# Generated by Django 5.1.4 on 2025-04-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilePic.jpeg', upload_to='profile_pic'),
        ),
    ]
