# Generated by Django 5.1.4 on 2025-03-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='https://images.app.goo.gl/k8ZHiLqpdqj6RLjv5', max_length=200),
        ),
    ]
